version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ep-proud-sky-a5lew77i.us-east-2.aws.neon.tech/cashback
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=mcdBKl32uJhV

spring-app:
  image: teste-cliente-login:latest
  ports: 
    - "8080:8080"
  environment:
    SPRING_DATASOURCE_URL:jdbc:postgresql://ep-proud-sky-a5lew77i.us-east-2.aws.neon.tech/cashback
  depends_on:
    - postgres-db